const STATUS = {
    APP_JUST_STARTED: "APP_JUST_STARTED",
    MOOD_SET: "MOOD_SET",
    API_CALL_IN_PROGRESS: "API_CALL_IN_PROGRESS",
    API_CALL_SUCCESSFUL: "API_CALL_SUCCESSFUL",
    API_CALL_ERRORED: "API_CALL_ERRORED",
};

export const {
    APP_JUST_STARTED,
    MOOD_SET,
    API_CALL_IN_PROGRESS,
    API_CALL_SUCCESSFUL,
    API_CALL_ERRORED,
} = STATUS;
